package io.neft.client;

public enum OutAction {
    // basic
    EVENT,

    // renderer
    SCREEN_SIZE,
    SCREEN_ORIENTATION,
    NAVIGATOR_LANGUAGE,
    NAVIGATOR_ONLINE,
    DEVICE_PIXEL_RATIO,
    DEVICE_IS_PHONE,
    POINTER_PRESS,
    POINTER_RELEASE,
    POINTER_MOVE,
    DEVICE_KEYBOARD_SHOW,
    DEVICE_KEYBOARD_HIDE,
    KEY_PRESS,
    KEY_HOLD,
    KEY_INPUT,
    KEY_RELEASE,
    IMAGE_SIZE,
    TEXT_SIZE,
    FONT_LOAD,
    NATIVE_ITEM_WIDTH,
    NATIVE_ITEM_HEIGHT,
    WINDOW_RESIZE,
    ITEM_KEYS_FOCUS
}
