enum OutAction: Int {
    case
    // basic
    EVENT = 0,
    
    // renderer
    SCREEN_SIZE,
    SCREEN_ORIENTATION,
    NAVIGATOR_LANGUAGE,
    NAVIGATOR_ONLINE,
    DEVICE_PIXEL_RATIO,
    DEVICE_IS_PHONE,
    POINTER_PRESS,
    POINTER_RELEASE,
    POINTER_MOVE,
    DEVICE_KEYBOARD_SHOW,
    DEVICE_KEYBOARD_HIDE,
    KEY_PRESS,
    KEY_HOLD,
    KEY_INPUT,
    KEY_RELEASE,
    IMAGE_SIZE,
    TEXT_SIZE,
    FONT_LOAD,
    SCROLLABLE_CONTENT_X,
    SCROLLABLE_CONTENT_Y
}
